<?php

declare(strict_types=1);

namespace Ws\Http\Tests\Unit\NanoGpt;

use PHPUnit\Framework\TestCase;
use Ws\Http\NanoGpt\AgentException;
use Ws\Http\NanoGpt\CommandExecKernel;
use Ws\Http\NanoGpt\Tool\CommandToolBase;
use Ws\Http\NanoGpt\Tool\FindTool;
use Ws\Http\NanoGpt\Tool\GrepTool;
use Ws\Http\NanoGpt\Tool\SedPrintTool;

/**
 * design/25 C2:CommandToolBase(骨架+参数槽/自动 schema/元字符拒绝/构造期校验)+ 内建示例。
 */
final class CommandToolTest extends TestCase
{
    private string $runtime;

    protected function setUp(): void
    {
        $this->runtime = sys_get_temp_dir() . '/ws-cmdtool-' . uniqid();
        mkdir($this->runtime, 0777, true);
    }

    protected function tearDown(): void
    {
        exec('rm -rf ' . escapeshellarg($this->runtime));
    }

    private function kernel(): CommandExecKernel
    {
        return new CommandExecKernel($this->runtime, 10, 2048);
    }

    // ---------- jsonSchema 自动生成 ----------

    public function testSchemaAutoGenerated(): void
    {
        $schema = (new GrepTool($this->kernel()))->jsonSchema();

        self::assertSame('object', $schema['type']);
        self::assertSame(['string', 'string'], array_column($schema['properties'], 'type'));
        self::assertSame(['pattern'], $schema['required'], 'required 槽进 required;default 槽不进');
        self::assertSame('Text pattern to search', $schema['properties']['pattern']['description']);
    }

    // ---------- 槽位校验 ----------

    public function testRequiredMissingRejected(): void
    {
        $result = (new GrepTool($this->kernel()))->execute(['path' => '.']);

        self::assertStringContainsString('missing required argument "pattern"', $result);
    }

    public function testSlotMetacharRejected(): void
    {
        $tool = new GrepTool($this->kernel());

        self::assertStringContainsString('forbidden character', $tool->execute(['pattern' => 'x; rm -rf /', 'path' => '.']));
        self::assertStringContainsString('forbidden character', $tool->execute(['pattern' => 'x | cat', 'path' => '.']));
        self::assertStringContainsString('forbidden character', $tool->execute(['pattern' => 'a$b', 'path' => '.']));
        self::assertStringContainsString('forbidden character', $tool->execute(['pattern' => '`id`', 'path' => '.']));
    }

    public function testDefaultSlotApplied(): void
    {
        file_put_contents($this->runtime . '/a.txt', "hello\nworld\nhello\n");

        $result = (new GrepTool($this->kernel()))->execute(['pattern' => 'hello']); // path 走 default '.'

        self::assertStringContainsString('exit: 0', $result);
        self::assertStringContainsString('hello', $result);
        self::assertSame(2, substr_count($result, 'a.txt:'), 'default path "." = runtime cwd 内递归命中两行');
    }

    // ---------- 内建示例工具真实执行 ----------

    public function testGrepToolRealRun(): void
    {
        file_put_contents($this->runtime . '/b.txt', "foo bar\nbaz\n");

        $result = (new GrepTool($this->kernel()))->execute(['pattern' => 'foo', 'path' => 'b.txt']);

        self::assertStringContainsString('exit: 0', $result);
        self::assertStringContainsString('foo bar', $result);
    }

    public function testFindToolRealRun(): void
    {
        file_put_contents($this->runtime . '/x.json', '{}');
        file_put_contents($this->runtime . '/y.txt', '');

        $result = (new FindTool($this->kernel()))->execute(['pattern' => '*.json', 'path' => '.']);

        self::assertStringContainsString('x.json', $result);
        self::assertStringNotContainsString('y.txt', $result);
    }

    public function testSedPrintToolRangeValidation(): void
    {
        file_put_contents($this->runtime . '/c.txt', "one\ntwo\nthree\n");
        $tool = new SedPrintTool($this->kernel());

        self::assertStringContainsString('range must match', $tool->execute(['range' => '5;20', 'path' => 'c.txt']));
        self::assertStringContainsString('range must match', $tool->execute(['range' => 'abc', 'path' => 'c.txt']));

        $ok = $tool->execute(['range' => '2,3', 'path' => 'c.txt']);
        self::assertStringContainsString('two', $ok);
        self::assertStringContainsString('three', $ok);
        self::assertStringNotContainsString('one', $ok);
    }

    // ---------- 构造期校验(类定义期安全) ----------

    public function testSkeletonOperatorRejectedAtConstruct(): void
    {
        try {
            new class($this->kernel()) extends CommandToolBase {
                public function name(): string
                {
                    return 'bad_pipe';
                }

                public function description(): string
                {
                    return 'd';
                }

                protected function template(): string
                {
                    return 'cat {path} | wc -l'; // 骨架含管道 → 构造期 613
                }

                protected function arguments(): array
                {
                    return ['path' => ['type' => 'string', 'description' => 'p', 'required' => true]];
                }
            };
            self::fail('expected AgentException 613');
        } catch (AgentException $e) {
            self::assertSame(613, $e->getCode());
            self::assertStringContainsString('shell operator', $e->getMessage());
        }
    }

    public function testSkeletonDenyBinaryRejectedAtConstruct(): void
    {
        try {
            new class($this->kernel()) extends CommandToolBase {
                public function name(): string
                {
                    return 'bad_rm';
                }

                public function description(): string
                {
                    return 'd';
                }

                protected function template(): string
                {
                    return 'rm -rf {path}'; // 黑名单二进制 → 构造期 613
                }

                protected function arguments(): array
                {
                    return ['path' => ['type' => 'string', 'description' => 'p', 'required' => true]];
                }
            };
            self::fail('expected AgentException 613');
        } catch (AgentException $e) {
            self::assertSame(613, $e->getCode());
            self::assertStringContainsString('is denied', $e->getMessage());
        }
    }
}
